version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-stock-streaming-kinesis-kafka"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1vtp5n4e7g2j6"
s3_prefix = "sam-stock-streaming-kinesis-kafka"
region = "us-east-2"
profile = "intrado_dev"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "CreationDate=\"2021-05-10\" StocksHost=\"apidojo-yahoo-finance-v1.p.rapidapi.com\" StocksApiKey=\"8996846c4emshda552bf12e48236p1c837cjsn213f3737a2a0\" TciStocksBucketName=\"adam-stocks-stream-kinesis-lambda\" StreamName=\"adam-stocks-stream-kinesis-lambda\" DeliveryStreamName=\"adam-stocks-stream-kinesis-lambda\" StocksSnsTopicName=\"adam-stocks-stream-kinesis-lambda\" SnsSubscriptionEmail=\"adam.mcquistan@thecodinginterface.com\" KafkaBootstrapServer=\"pkc-4nym6.us-east-1.aws.confluent.cloud:9092\" KafkaSecurityProtocol=\"SASL_SSL\" KafkaSaslMechanism=\"PLAIN\" KafkaSaslUsername=\"THWIQSNGUKL52NSX\" KafkaSaslPassword=\"+Nr8P1gUJhMnRZ3DCeWeR4hSuLsGqdulWM25d09hBWOd7Fj9noHcGyjFwWW11SYw\" KafkaTopic=\"stocks\""
